# Generated by Django 5.1 on 2024-08-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(blank=True, db_column='Data_Time', null=True)),
                ('num_sens', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='Num_Sens', max_length=50, null=True)),
                ('temperature', models.FloatField(blank=True, db_column='Temperature', null=True)),
                ('vlagnost', models.FloatField(blank=True, db_column='Vlagnost', null=True)),
                ('tochka_rosa', models.FloatField(blank=True, db_column='Tochka_Rosa', null=True)),
                ('status_sens', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='Status_sens', max_length=1, null=True)),
            ],
            options={
                'db_table': 'Parametr_T',
                'managed': False,
            },
        ),
    ]
